import { useQuery } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { endpoints } from '../services/api';

export function Analytics() {
  const { data } = useQuery({ queryKey:['analytics'], queryFn:endpoints.analytics, refetchInterval:30000 });
  const languages = Object.entries(data?.languages || {}).map(([language, files]) => ({ language, files }));
  const contributors = Object.entries(data?.topContributors || {}).map(([author, prs]) => ({ author, prs }));
  return <div className="space-y-6"><div><p className="text-sm text-indigo-300">Analytics</p><h1 className="text-3xl font-black text-white">Engineering Intelligence</h1><p className="mt-2 text-sm text-zinc-500">No fake numbers. Every chart is derived from backend PR, review, and vector data.</p></div>
  <div className="grid gap-4 md:grid-cols-3"><Metric label="Files analyzed" value={data?.filesAnalyzed || 0}/><Metric label="Review accuracy" value={`${data?.reviewAccuracy || 0}%`}/><Metric label="Languages" value={languages.length}/></div>
  <div className="grid gap-6 lg:grid-cols-2"><Panel title="PRs/day"><ResponsiveContainer height={300}><BarChart data={data?.prsPerDay || []}><CartesianGrid strokeDasharray="3 3" stroke="#27272a"/><XAxis dataKey="day" stroke="#71717a"/><YAxis stroke="#71717a"/><Tooltip contentStyle={{background:'#18181b',border:'1px solid #3f3f46'}}/><Bar dataKey="prs" fill="#6366f1" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Review scores"><ResponsiveContainer height={300}><LineChart data={data?.scores || []}><CartesianGrid strokeDasharray="3 3" stroke="#27272a"/><XAxis dataKey="pr" stroke="#71717a"/><YAxis stroke="#71717a"/><Tooltip contentStyle={{background:'#18181b',border:'1px solid #3f3f46'}}/><Line dataKey="quality" stroke="#818cf8"/><Line dataKey="security" stroke="#34d399"/><Line dataKey="complexity" stroke="#f59e0b"/></LineChart></ResponsiveContainer></Panel><Panel title="Languages"><div className="space-y-3">{languages.map((r:any)=><div key={r.language} className="flex justify-between rounded-xl bg-zinc-950 p-3 text-sm"><span>{r.language}</span><span className="text-indigo-300">{r.files}</span></div>)}</div></Panel><Panel title="Top contributors"><div className="space-y-3">{contributors.map((r:any)=><div key={r.author} className="flex justify-between rounded-xl bg-zinc-950 p-3 text-sm"><span>{r.author}</span><span className="text-indigo-300">{r.prs} PRs</span></div>)}</div></Panel></div></div>;
}
function Metric({label,value}:any){return <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-3xl font-black text-white">{value}</p></div>}
function Panel({title,children}:any){return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6"><h2 className="mb-4 font-bold text-white">{title}</h2>{children}</section>}
